### ISSUE TITLE
[BUG]: Tour Name / Description is deleted after updating coordinates of markers

### ISSUE THREAD

**Issue by Saela** [gipfeli-io/gipfeli-frontend#31]
### Description of the bug

When you create a new tour, set a tour name or description and then set a marker the tour name / description gets removed. It does not happen when you set the markers first and then update the tour name and description.

### Steps To Reproduce

1. Go to tour list
2. Click on Add Tour
3. Set a title
4. Set a marker on the map

**Comment by Tugark** [comment]
It also does not work if you edit an existing tour, change e.g. the title and then move a point - it will reset the title.

I believe the issue is that we're passing down the handle function wich somehow does not get state updates in the parent and always overrides with the state it had in the beginning. That's also the reason why it works when you change it the other way around.

Another issue I found is that we're calling the inithooks many times because everything is in the useEffect() hook. I'm trying to work on that now.

**Comment by Tugark** [comment]
Funny thing is: the statehandler gets called for each character in the input fields, and they are then reduced by one character :D

![image](https://user-images.githubusercontent.com/16555423/170865626-83c9677b-0b71-41dd-b2f1-d7bdf7774db9.png)

**Comment by Tugark** [comment]
Yes, I think that is the issue:

1. We listen to handlerChange as useEffect dependency
2. When we type in the input fields, for each character, we pass down a new eventhandler which has the new currentState attached
3. The eventhandlers are called in order - and because our first state is an empty one, it gets reduced one by one to the initial state. 


I think we have to entangle the whole logic - the handlers should only be attached once and call the replaced function.

**Comment by Tugark** [comment]
We fixed this with Tobias, pushed in this commit: https://github.com/gipfeli-io/gipfeli-frontend/commit/3414190e7049d7d401460e237c91ddbcae14aa39

The issue was that we were passing a function that always got a wrong reference, and we also use `setState` wrong.
