### ISSUE TITLE
Switch from NextJS to React

### ISSUE THREAD

**Issue by Saela** [gipfeli-io/gipfeli-frontend#34]
We decided to ditch NextJS and use React for the frontend. 

- Handle multiple layouts
- Handle auth

# Review

- [x] Code is written
- [ ] Tests (if necessary) are written
- [ ] Code is documented (either in documentation itself or in code)
- [x] Code is reviewed
- [x] Must implement functionality specified in the ticket and in line with the design specifications (e.g. wireframes)
- [x] Build is successful (including all tests passed)
- [x] Deployment to staging works
- [ ] Manual testing on staging by peer

**Comment by Tugark** [comment]
@Saela This was the fix for the deployment to really work: https://github.com/gipfeli-io/gipfeli-frontend/commit/011addbe4e7f9734a9fe3897115ff8deedf1bd42

🤷 😆 I did not have to change anything in Cloudrun, as we're already exposing the `$PORT` variable.

We're officially nextjs-free and have added some quite nice features along the way :D
